export const COMMENTS_LIST_REQUEST = "COMMENTS_LIST_REQUEST";
export const COMMENTS_LIST_SUCCESS = "COMMENTS_LIST_SUCCESS";
export const COMMENTS_LIST_FAIL = "COMMENTS_LIST_FAIL";

export const COMMENTS_CREATE_REQUEST = "COMMENTS_CREATE_REQUEST";
export const COMMENTS_CREATE_SUCCESS = "COMMENTS_CREATE_SUCCESS";
export const COMMENTS_CREATE_FAIL = "COMMENTS_CREATE_FAIL";

export const COMMENTS_UPDATE_REQUEST = "COMMENTS_UPDATE_REQUEST";
export const COMMENTS_UPDATE_SUCCESS = "COMMENTS_UPDATE_SUCCESS";
export const COMMENTS_UPDATE_FAIL = "COMMENTS_UPDATE_FAIL";

export const COMMENTS_DELETE_REQUEST = "COMMENTS_DELETE_REQUEST";
export const COMMENTS_DELETE_SUCCESS = "COMMENTS_DELETE_SUCCESS";
export const COMMENTS_DELETE_FAIL = "COMMENTS_DELETE_FAIL";


export const COMMENTS_LIKE_REQUEST = "COMMENTS_LIKE_REQUEST";
export const COMMENTS_LIKE_SUCCESS= "COMMENTS_LIKE_SUCCESS";
export const COMMENTS_LIKE_FAIL ="COMMENTS_LIKE_FAIL";

export const COMMENTS_REPLY_REQUEST = "COMMENTS_REPLY_REQUEST";
export const COMMENTS_REPLY_SUCCESS = "COMMENTS_REPLY_SUCCESS";
export const COMMENTS_REPLY_FAIL = "COMMENTS_REPLY_FAIL";

export const COMMENTS_LIST_REPLY_REQUEST = "COMMENTS_LIST_REPLY_REQUEST";
export const COMMENTS_LIST_REPLY_SUCCESS = "COMMENTS_LIST_REPLY_SUCCESS";
export const COMMENTS_LIST_REPLY_FAIL = "COMMENTS_LIST_REPLY_FAIL";

