export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_SENDOTP_FAIL = "USER_SENDOTP_FAIL";
export const USER_SENDOTP_SUCCESS = "USER_SENDOTP_SUCCESS";
export const USER_SENDOTP_REQUEST = "USER_SENDOTP_REQUEST";

export const  USER_VERIFYOTP_SUCCESS= "USER_VERIFYOTP_SUCCESS";
export const  USER_VERIFYOTP_FAIL= "USER_VERIFYOTP_FAIL";
export const  USER_VERIFYOTP_REQUEST="USER_VERIFYOTP_REQUEST";

